spring.application.name=database-demo

# H2 Database Configuration (commented for now)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=postgresxem
#spring.datasource.password=postgresxem
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:8080/databasedemo
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgresxem
spring.datasource.password=postgresxem
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.hibernate.ddl-auto=update
