spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/acosta_db
spring.datasource.username=acosta_user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
