spring.application.name=api-demo
# Server configuration
server.port=8080

# Application info
app.name=Nepomuceno Spring Boot API
app.version=1.0.0

# Logging
logging.level.com.nepomuceno.springboot=DEBUG