
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/oop_lab
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Automatically detects PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE