spring.application.name=rodenas

spring.application.name=rodenas

spring.datasource.url=jdbc:postgresql://localhost:5432/studentsdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true