spring.application.name=api-demo

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/apidemo
spring.datasource.username=postgres
spring.datasource.password=dmisles2007
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.com.nu.bscs.b=DEBUG
