name: Build Java Files

on:
  push:
    branches: [ main,develop-* ]
  pull_request:
    branches: [ main, develop-* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Compile All Java Files
        run: |
          mkdir -p bin
          javac -d bin $(find . -name "*.java")
